/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.JohnnyTests.NettySimpleChat.gui;

import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.SimpleChannelInboundHandler;

/**
 * 
 * @author johnny
 */
public class ChatGUIClient extends javax.swing.JFrame
{
	private NettyTCPClient tcpClient;

	/**
	 * Creates new form NewJFrame
	 */
	public ChatGUIClient()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		send_Button = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		receive_msg_textbox = new javax.swing.JTextArea();
		msg_textbox = new javax.swing.JTextField();
		ip_textbox = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		connect_button = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		port_textbox = new javax.swing.JTextField();
		clear_button = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Chat GUI Client");

		send_Button.setText("Send");
		send_Button.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				send_ButtonActionPerformed(evt);
			}
		});

		receive_msg_textbox.setEditable(false);
		receive_msg_textbox.setColumns(20);
		receive_msg_textbox.setRows(5);
		jScrollPane1.setViewportView(receive_msg_textbox);

		msg_textbox.setText("test");

		ip_textbox.setText("127.0.0.1");

		jLabel1.setText("IP:");

		connect_button.setText("Connect");
		connect_button.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				connect_buttonActionPerformed(evt);
			}
		});

		jLabel2.setText("Port:");

		jLabel3.setText("Message:");

		port_textbox.setText("9999");

		clear_button.setText("Clear");
		clear_button.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				clear_buttonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(11, 11, 11)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING,
														false)
												.add(layout
														.createSequentialGroup()
														.add(jLabel1)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(ip_textbox,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																145,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel2)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(port_textbox,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																54,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(18, 18, 18)
														.add(connect_button,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
												.add(layout
														.createSequentialGroup()
														.add(jLabel3)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(msg_textbox,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																251,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(send_Button)))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(clear_button)
										.add(0, 21, Short.MAX_VALUE))
								.add(layout.createSequentialGroup()
										.addContainerGap().add(jScrollPane1)))
						.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(12, 12, 12)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(ip_textbox,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel1)
								.add(connect_button)
								.add(jLabel2)
								.add(port_textbox,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(send_Button)
								.add(msg_textbox,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel3).add(clear_button))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								328, Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void send_ButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_send_ButtonActionPerformed
		// TODO add your handling code here:
		tcpClient.sendMessage(msg_textbox.getText() + "\n");
		receive_msg_textbox.append(msg_textbox.getText() + "\n");
	}// GEN-LAST:event_send_ButtonActionPerformed

	private void connect_buttonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_connect_buttonActionPerformed
		// TODO add your handling code here:

		if (connect_button.getText().equals("Connect"))
		{
			final String ipString = ip_textbox.getText();
			final int portNum = Integer.parseInt(port_textbox.getText());

			tcpClient = new NettyTCPClient(ipString, portNum);
			tcpClient.setHandler(new SimpleChannelInboundHandler<String>()
			{
				@Override
				protected void channelRead0(ChannelHandlerContext arg0,
						final String msg) throws Exception
				{
					java.awt.EventQueue.invokeLater(new Runnable()
					{
						public void run()
						{
							receive_msg_textbox.append(msg + "\n");
						}
					});
				}

				@Override
				public void channelActive(ChannelHandlerContext ctx)
						throws Exception
				{
					connect_button.setText("Disconnect");
				}

				@Override
				public void channelInactive(ChannelHandlerContext ctx)
						throws Exception
				{
					java.awt.EventQueue.invokeLater(new Runnable()
					{
						public void run()
						{
							receive_msg_textbox.append("Offline...\n");
						}
					});
					System.out.println("Offline...");
					connect_button.setText("Connect");
				}

			});

			try
			{
				tcpClient.startClient();
			} catch (Exception e)
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
				receive_msg_textbox.append(e.getMessage()+"\n");
				connect_button.setText("Connect");
			}
		} else if (connect_button.getText().equals("Disconnect"))
		{
			if (tcpClient != null)
				tcpClient.stopClient();
		}
	}// GEN-LAST:event_connect_buttonActionPerformed

	private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_clear_buttonActionPerformed
		// TODO add your handling code here:
		receive_msg_textbox.setText("");
	}// GEN-LAST:event_clear_buttonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(ChatGUIClient.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(ChatGUIClient.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(ChatGUIClient.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(ChatGUIClient.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new ChatGUIClient().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton clear_button;
	private javax.swing.JButton connect_button;
	private javax.swing.JTextField ip_textbox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField msg_textbox;
	private javax.swing.JTextField port_textbox;
	private javax.swing.JTextArea receive_msg_textbox;
	private javax.swing.JButton send_Button;
	// End of variables declaration//GEN-END:variables
}
